@user = <username>
@pass = <password

GET https://sap-api-layer.azurewebsites.net/api/swagger/json
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET http://localhost:7051/api/GetSalesOrder?num=4662
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET http://localhost:7051/api/GetSalesOrderList
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET http://localhost:7051/api/GetPurchaseOrder?num=4500001303
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET http://localhost:7051/api/GetPurchaseOrderList
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET https://sap-api-layer.azurewebsites.net/api/GetSalesOrder?num=4662
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET https://sap-api-layer.azurewebsites.net/api/GetSalesOrderList
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET https://sap-api-layer.azurewebsites.net/api/GetPurchaseOrder?num=4500001303
content-type: application/json
Authorization: Basic {{user}}:{{pass}}

###

GET https://sap-api-layer.azurewebsites.net/api/GetPurchaseOrderList
content-type: application/json
Authorization: Basic {{user}}:{{pass}}
